apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-repo-creds
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-repo-store
    kind: ClusterSecretStore
  target:
    name: argocd-repo-creds
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: {{ .Values.workloadsRepoURL | quote }}
        sshPrivateKey: "{{ `{{ .sshPrivateKey }}` }}"
  data:
    - secretKey: sshPrivateKey
      remoteRef:
        {{- if eq .Values.secretStoreType "vault" }}
        key: {{ trimPrefix "secret/data/" .Values.vaultSecretPath | quote }}
        property: sshPrivateKey
        {{- else if eq .Values.secretStoreType "aws-ssm" }}
        key: {{ .Values.ssmParameterPath | quote }}
        {{- else if eq .Values.secretStoreType "azure-keyvault" }}
        key: {{ .Values.azureSecretName | quote }}
        {{- end }}
