apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: platform-trust-bundle
spec:
  sources:
    - inLine: |
        {{ .Values.trustedCaPemB64 | b64dec | trim | nindent 8 }}
    {{- if .Values.caChainSecretName }}
    - secret:
        name: {{ .Values.caChainSecretName }}
        key: tls.crt
    {{- end }}
    - useDefaultCAs: true
  target:
    configMap:
      key: ca-bundle.crt
    namespaceSelector:
      matchLabels: {}
