secretStoreType: ""
repoCredsUrlPrefix: ""
repoCredsUsername: ""   # required when repoCredsUrlPrefix is https (token auth)
vaultAddr: ""
vaultRole: ""
vaultAuthMountPath: "kubernetes"
vaultSecretPath: ""
awsRegion: ""
ssmParameterPath: ""
azureKeyVaultUrl: ""
azureTenantId: ""
azureSecretName: ""
